// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMYwnnXK6Ql6VXeqrwbrPLpN3GTU1qD8',
    appId: '1:93493688303:web:2e312e7ad175212e08e81a',
    messagingSenderId: '93493688303',
    projectId: 'mywallet-46595',
    authDomain: 'mywallet-46595.firebaseapp.com',
    storageBucket: 'mywallet-46595.firebasestorage.app',
    measurementId: 'G-Z0V4M7E2LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1xRn_H9wKK7QSd4B6nlICOgAlVZYq1K0',
    appId: '1:93493688303:android:0a5ed0a4abf6b9ef08e81a',
    messagingSenderId: '93493688303',
    projectId: 'mywallet-46595',
    storageBucket: 'mywallet-46595.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALMYwnnXK6Ql6VXeqrwbrPLpN3GTU1qD8',
    appId: '1:93493688303:web:2cfcf3ce49a700fe08e81a',
    messagingSenderId: '93493688303',
    projectId: 'mywallet-46595',
    authDomain: 'mywallet-46595.firebaseapp.com',
    storageBucket: 'mywallet-46595.firebasestorage.app',
    measurementId: 'G-80YTK8QMZ3',
  );
}
